server:
  port: 3000

enginePlatformUrl: http://127.0.0.1:4001
xtUrl: http://127.0.0.1:4001
url0: http://127.0.0.1:4001
url1: http://127.0.0.1:4001
url2: http://127.0.0.1:4001
url3: http://127.0.0.1:4001
url4: http://127.0.0.1:4001
url5: http://127.0.0.1:4001
url6: http://127.0.0.1:4001

engineQTime: 3

# spring config
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/znt?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
# 如果使用达梦数据库，注释上面的 datasource，打开以下配置
#  datasource:
#    url: jdbc:dm://127.0.0.1:5236
#    driver-class-name: dm.jdbc.driver.DmDriver
#    username: SYSDBA
#    password: Sanbu123

  redis:
    password: 123456
    host: localhost
    port: 6379


# logging config
logging:
  file:
    name: logs/myapp.log
    max-size: 10MB
    max-history: 30
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
